iframe_cookie_consent.settings:
  type: config_object
  label: 'Cookie consent settings'
  mapping:
    policy_library:
      type: mapping
      mapping:
        cookieconsent_settings:
          type: text
          label: 'Cookie consent settings'
